# vscode:
#   extensions:
#     - redhat.java
#     - vscjava.vscode-java-dependency
#     - vscjava.vscode-java-debug
#     - vscjava.vscode-maven
#     - vscjava.vscode-java-test
#     - https://github.com/redhat-developer/vscode-rsp-ui/releases/download/v0.23.11/rsp-ui-0.23.11-78.vsix
#     - https://github.com/gitkraken/vscode-gitlens/releases/download/v11.7.0/gitlens-11.7.0.vsix
#     - redhat.fabric8-analytics
#     - https://github.com/microsoft/vscode-docker/releases/download/v1.20.0/vscode-docker-1.20.0.vsix
#     - mhutchie.git-graph
#     - pivotal.vscode-spring-boot
#     - vscjava.vscode-spring-initializr
#     - vscjava.vscode-spring-boot-dashboard
#     - anweber.vscode-httpyac
#     - rangav.vscode-thunder-client
#     - cweijan.vscode-postgresql-client2